# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4119b0b47ec3a95ac27917e840b20e8ed0ac6cfdfae5703ba3df89232b65321b35f5489c1d451ee99c404e338aa2acb39538ae17b7ffd4afeb1a186dfb85947

test:
  secret_key_base: fb16c0ee23e4b255a4d5020c49a3136acc973b6ef990953664bba0976a5390b833021f3cb5fded6ad593008d82065125f838b6748b4bd39b63d7a4d30d03682a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
